# Generated by Django 6.0.5 on 2026-07-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userprogress_unique_together_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='starter_code',
            field=models.TextField(default=''),
        ),
    ]
