# Generated by Django 6.0.5 on 2026-07-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_hardwaresystem_hardwarechallenge_hardwareprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='example_output',
            field=models.TextField(default=''),
        ),
    ]
